from flask import Blueprint, request, jsonify

backtracking = Blueprint('backtracking', __name__,url_prefix='/backtracking')
nmdsnssjkskjkjdmsmsdhkjsdjkdsjldsioiewkjwennmsdmndsmnsjkkjsljsjksdjkd
hfdhdhdhhdmnsmndsmnmnsnmsdmndsmnsdnmdsmnsdjkweuiowweewjkjkewnmdmndmndsnns
hgfkdkslkdsklksdklsdkldskldsklsdndsnmdsjwekjewkjewkjemsmsms,,s,snnsnmsmsmsm
fuejhweouhjwdajhefwjhefnklwfejknlefjnkfe